//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int idCuenta { get; set; }
        public string contrasenaCuenta { get; set; }
        public string emailCuenta { get; set; }
        public Nullable<System.DateTime> fechaAltaCuenta { get; set; }
        public Nullable<System.DateTime> fechaBajaCuenta { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idPremium { get; set; }
    }
}
