//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaNotificacion
    {
        public int idCuentaNotificacion { get; set; }
        public Nullable<System.DateTime> fechaAltaNotificacion { get; set; }
        public Nullable<System.DateTime> fechaBajaNotificacion { get; set; }
        public Nullable<int> idNotificacion { get; set; }
        public Nullable<int> idCuenta { get; set; }
    }
}
