//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int idDireccion { get; set; }
        public Nullable<int> idLote { get; set; }
        public Nullable<int> idManzana { get; set; }
        public string nombreBarrio { get; set; }
        public string nombreCalle { get; set; }
        public Nullable<int> numeroCalle { get; set; }
        public Nullable<int> idLocalidad { get; set; }
    }
}
