//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inmobiliaria
    {
        public int idInmobiliaria { get; set; }
        public Nullable<System.DateTime> altaInscripcion { get; set; }
        public Nullable<int> cuitInmobiliaria { get; set; }
        public string nombreInmobiliaria { get; set; }
        public string telefonoInmobiliaria { get; set; }
        public Nullable<int> idCuenta { get; set; }
        public Nullable<int> idDireccion { get; set; }
    }
}
