//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemReseña
    {
        public int idItemReseña { get; set; }
        public Nullable<bool> IR_esAI { get; set; }
        public Nullable<bool> IR_esAoAr { get; set; }
        public Nullable<bool> IR_esArAo { get; set; }
        public string nombreItemReseña { get; set; }
    }
}
