//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultimediaInmueble
    {
        public int idMultimediaInmueble { get; set; }
        public string urlMultimediaInmueble { get; set; }
        public Nullable<int> idInmueble { get; set; }
    }
}
