//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        public string apellidoPropietario { get; set; }
        public int idPropietario { get; set; }
        public string nombrePropietario { get; set; }
        public Nullable<int> numeroDocumentoProp { get; set; }
        public string telefonoPropietario { get; set; }
        public string tipoDocumentoProp { get; set; }
        public Nullable<int> idCuenta { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
