//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicacionEstado
    {
        public int idPublicacionEstado { get; set; }
        public Nullable<System.DateTime> fechaAltaPublicacionEstado { get; set; }
        public Nullable<System.DateTime> fechaBajaPublicacionEstado { get; set; }
        public Nullable<int> idEstadoPublicacion { get; set; }
        public Nullable<int> idPublicacion { get; set; }
    }
}
