//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public int idPublicacion { get; set; }
        public string descripcionPublicacion { get; set; }
        public Nullable<System.DateTime> fechaAltaPublicacion { get; set; }
        public Nullable<System.DateTime> fechaBajaPublicacion { get; set; }
        public Nullable<decimal> precioAlquiler { get; set; }
        public string tituloPublicacion { get; set; }
        public Nullable<int> idInmueble { get; set; }
    }
}
