//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReseñaArrendadorArrendatario
    {
        public int idReseñaAoAr { get; set; }
        public string descripcionReseñaAoAr { get; set; }
        public Nullable<System.DateTime> fechaAltaReseñaAoAr { get; set; }
        public Nullable<System.DateTime> fechaBajaReseñaAoAr { get; set; }
        public Nullable<decimal> puntuacionReseñaAoAr { get; set; }
        public string respuestaReseñaAoAr { get; set; }
        public Nullable<int> idAlquiler { get; set; }
    }
}
