//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReseñaArrendatarioInmueble
    {
        public int idReseñaAI { get; set; }
        public string descripcionReseñaAI { get; set; }
        public Nullable<System.DateTime> fechaAltaReseñaAI { get; set; }
        public Nullable<System.DateTime> fechaBajaReseñaAI { get; set; }
        public Nullable<decimal> puntuacionReseñaAI { get; set; }
        public string respuestaReseñaAI { get; set; }
        public Nullable<int> idAlquiler { get; set; }
    }
}
