//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReseñaArrendadorArrendatario
    {
        public int idReseñaArAo { get; set; }
        public string descripcionReseñaArAo { get; set; }
        public Nullable<System.DateTime> fechaAltaReseñaArAo { get; set; }
        public Nullable<System.DateTime> fechaBajaReseñaArAo { get; set; }
        public Nullable<int> puntuacionReseñaArAo { get; set; }
        public string respuestaReseñaArAo { get; set; }
        public Nullable<int> idAlquiler { get; set; }
    }
}
