//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReseñaItemAI
    {
        public int idReseñaItemAI { get; set; }
        public Nullable<int> puntuacionReseñaItemAI { get; set; }
        public Nullable<int> idReseñaAI { get; set; }
        public Nullable<int> idItemReseña { get; set; }
    }
}
