//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReseñaItemArAo
    {
        public int idReseñaItemArAo { get; set; }
        public Nullable<int> puntuacionReseñaItemArAo { get; set; }
        public Nullable<int> idReseñaArAo { get; set; }
        public Nullable<int> idItemReseña { get; set; }
    }
}
