//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrendaSysModelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        public int idURL { get; set; }
        public string linkURL { get; set; }
        public Nullable<bool> seMuestra { get; set; }
        public string descripcion { get; set; }
        public string codigo { get; set; }
        public Nullable<int> posicion { get; set; }
        public string nombre { get; set; }
        public string iconClass { get; set; }
    }
}
